services:
  dashboard-app:
    image: mariadb:11.8.6
    container_name: dashboard-app
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - compose-net
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123456

volumes:
  mariadb_data:

networks:
  compose-net:
    driver: bridge